#!/bin/sh
PREV_BRANCH=$1
CURRENT_BRANCH=$2

COLOR_DEFAULT='\033[0m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'

if [ $PREV_BRANCH != $CURRENT_BRANCH ]; then
    DIFF=`git diff-tree --diff-filter=AMTUB --no-commit-id --name-only -r $PREV_BRANCH $CURRENT_BRANCH | grep composer.lock`
    if [ $DIFF = "composer.lock" ]; then
        echo "${COLOR_GREEN}git post-checkout hook run"
        echo "see https://git-scm.com/docs/githooks#_post_checkout${COLOR_DEFAULT}"
    	echo "${COLOR_YELLOW}composer.lock has changed.\nAutorun composer install${COLOR_DEFAULT}";
    	composer --no-interaction install;
        echo "${COLOR_GREEN}end run post-checkout${COLOR_DEFAULT}"
    fi
fi

exit 0